import Link from "next/link";
export default function Home() {
  return <>
    <header className="nav shell"><Link className="brand" href="/"><b>TT</b><span>Tyler Thibault</span></Link><nav><a href="#services">What I make</a><a href="#work">Work</a><a href="#about">Why me</a><a href="/store">Store</a><a href="/creative-circle">Creative Circle</a></nav><a className="nav-cta" href="#contact">WORK WITH ME <span style={{color:"var(--lime)"}}>↗</span></a></header>
    <main>
      <section className="hero"><div className="status-pill"><i/> AVAILABLE FOR CREATIVE PROJECTS</div><div className="hero-grid"><div><p className="eyebrow">CREATOR × BUILDER × PROBLEM SOLVER</p><h1>I build things.<br/>I explain things.<br/><span className="outline">I make them</span> <span className="blue">matter.</span></h1><p className="lead">Content, UGC, software, AI, digital products, and creative experiments — built with clear thinking, hands-on problem solving, and enough personality to make people care.</p><div className="actions"><a className="btn primary" href="#work">SEE MY WORK ↘</a><a className="btn secondary" href="#services">WHAT I MAKE</a></div></div><div className="hero-visual"><div className="sticker">REAL HUMAN<br/>ENERGY ↗</div><div className="sticker cyan">IDEAS MADE<br/>CLEAR</div><div className="creator-card"><div className="creator-screen"><span className="micro">CREATOR / BUILDER</span><div className="orbit">TT</div><h2>Different medium. Same goal. <span style={{color:"var(--lime)"}}>Make it useful, clear, and engaging.</span></h2></div></div></div></div><div className="hero-fit"><span>WHAT I DO</span><b>CONTENT + UGC</b><b>AI + SOFTWARE</b><b>DIGITAL PRODUCTS</b><b>CREATIVE PROJECTS</b></div></section>
      <div className="ticker"><div>CONTENT THAT CONNECTS ✦ PRODUCTS THAT WORK ✦ IDEAS MADE CLEAR ✦ BUILT TO BE USEFUL ✦ CONTENT THAT CONNECTS ✦ PRODUCTS THAT WORK ✦ IDEAS MADE CLEAR ✦ BUILT TO BE USEFUL ✦</div></div>
      <section className="section shell" id="services"><div className="section-head"><div><span>01 / WHAT I DO</span><h2>Different tools.<br/><b>Same goal.</b></h2></div><p>I work across content, technology, products, and creative projects. The common thread is turning an idea into something clear, useful, and engaging.</p></div><div className="strips">{[["01","CONTENT + UGC","Make the idea worth watching.","Short-form video, product demos, social content, and creator-led storytelling."],["02","AI + SOFTWARE","Turn complicated into useful.","Tools, workflows, prototypes, and explanations that make technology easier to use."],["03","PRODUCTS + PROJECTS","Take an idea off the whiteboard.","Digital products, experiments, physical products, and whatever is worth building next."],["04","EXPLAINERS + EDUCATION","Make the hard thing click.","Clear communication, demonstrations, memory techniques, and practical teaching."]].map(x=><article className="strip" key={x[0]}><span>{x[0]}</span><div><small>{x[1]}</small><h3>{x[2]}</h3></div><p>{x[3]}</p><strong>↗</strong></article>)}</div></section>
      <section className="section shell" id="work"><div className="section-head"><div><span>02 / SELECTED WORK</span><h2>Things I’ve <b>made.</b></h2></div><p>A mix of content, software, experiments, and products. Different outputs, but the same habit: find the problem, understand it, and make something better.</p></div><div className="work-grid"><article className="feature large"><div className="feature-art"><span className="micro">01 / BUILD — SOFTWARE + TOOLS</span><div className="big">SOLVE THE<br/>ANNOYING<br/>PROBLEM.</div></div><div className="feature-copy"><small>BUILDER PROJECTS</small><h3>Software, plugins, workflows, and tools.</h3><p>Built around real friction instead of abstract feature lists.</p></div></article><article className="feature"><div className="feature-art"><span className="micro">02 / CREATE</span><div className="big">STOP<br/>SCROLLING.</div></div><div className="feature-copy"><small>CREATOR WORK</small><h3>Turn the idea into a story.</h3><p>Hooks, demonstrations, product content, and short-form built for attention.</p></div></article><article className="feature"><div className="feature-art" style={{background:"linear-gradient(145deg,#123e6d,#0d1926 66%,#0d1016)"}}><span className="micro">03 / EXPLAIN</span><div className="big">HOOK →<br/>IDEA →<br/>PAYOFF</div></div><div className="feature-copy"><small>EXPLAINERS</small><h3>Teach something that sticks.</h3><p>Technology, memory, workflows, and useful ideas made easier to understand.</p></div></article></div></section>
      <section className="proof" id="about"><div className="shell proof-grid"><div><span className="micro">03 / ABOUT</span><h2>I like figuring out <b style={{color:"var(--lime)"}}>how things work.</b></h2><p className="muted">I’m a creator and a builder. That has taken me through software development, AI, content creation, mnemonic techniques, UGC, digital products, and a growing list of experiments.</p></div><div className="facts">{[["01","Creator mindset","Story, clarity, attention"],["02","Builder mindset","Problems, systems, solutions"],["03","Technical fluency","AI, apps, software, workflows"],["04","Flexible output","Content, tools, products, ideas"]].map(x=><div className="fact" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</div></div></section>
      <footer className="contact" id="contact"><div className="shell contact-inner"><div><small className="micro">READY WHEN YOU ARE</small><h2>Bring me<br/>the idea.<br/><span className="blue">Let’s make something.</span></h2></div><a className="circle-cta" href="mailto:hello@thibaultsolutions.com">EMAIL<br/>TYLER ↗</a></div></footer>
    </main>
  </>;
}
