import { mkdir, rm } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import { filterForEffect } from "../src/lib/effects/export.ts";

const cases: Array<[string, Record<string,string|number|boolean>]> = [
["horizontal-band-shift",{shift:28}],["binary-grid",{size:14,threshold:.5}],["digital-rain",{density:.55,brightness:1.2,scale:14}],["block-pixelation",{size:18}],["eroded-halftone",{contrast:1.6,noise:.2}],["ascii-symbols",{size:14,contrast:1.4}],["ember-glyphs",{glow:8}],["topographic-lines",{threshold:.5}],["neon-edge-trace",{sensitivity:.35,glow:7}],["repeated-crop-grid",{columns:3,rows:3}],["cross-stitch-pixels",{size:10,thickness:2}],["date-stamp-burn",{dateText:"09 24 26",opacity:.85,scale:1}],["variable-dot-matrix",{grid:10,contrast:1.4}],["mirror-side-panels",{blur:6}],["polygon-fragmentation",{rotation:8,displacement:22,count:12,gap:2}],["progressive-blur",{blur:12}],["glitch-bloom",{chromatic:5,intensity:1,radius:7}],["datamosh-smear",{persistence:5,feedback:.65}],["motion-study-grid",{spacing:3}],["film-gate-flicker",{exposure:.16,grain:.18}],["ghost-double-print",{opacity:.45,x:8,y:4}],["diagonal-frame-fracture",{angle:28}],["technical-pen-hatching",{contrast:1.5,density:8,thickness:1}],["thermal-hud",{hud:.65}],["fisheye-lens",{strength:.3,centerX:.5,centerY:.5}],["wavy-scanlines",{amplitude:8,spacing:6,thickness:1}],["luminance-flow",{sensitivity:.5,curvature:.5,length:12}],["particle-reconstruction",{movement:3}],["mirror-double-exposure",{opacity:.55}],["monochrome-dither",{contrast:1.4,threshold:.5}],["machine-vision-overlay",{thickness:1,color:"#a3ff12"}],["quantized-pixel-art",{resolution:14,palette:8}],["magazine-halftone",{contrast:1.4,frequency:8,size:4}],["crt-phosphor-mesh",{mesh:3,scanline:.4,glow:5}],["cmyk-misregistration",{magenta:5,yellow:2,cyan:-4,texture:.18}],["retro-lcd-screen",{cell:7,ghosting:.35}],["rgb-prism-slices",{separation:8,angle:0}],["relief-grid-3d",{depth:8,density:10}],["analog-scan-tear",{shift:20,noise:.15,jitter:.3}],["screen-print-layers",{texture:.25}],["liquid-ink-bleed",{radius:7}],["geometric-masks",{size:.25,count:8,invert:false}],["risograph-dots",{contrast:1.4,offset:4,noise:.18,frequency:8}],["survey-data-overlay",{grid:40,thickness:1,opacity:.65}],["vhs-tape-damage",{chroma:5,noise:.2}],["woven-thread-pixels",{size:8,thickness:2}],["mosaic-tile-scatter",{tile:18,rotation:8}],["puzzle-collage",{pieces:12,border:1,displacement:14}],["slit-scan-time-slices",{span:.5,width:10,direction:"vertical"}],["photocopier-toner",{contrast:2,threshold:.5,noise:.25}],["microtext-portrait",{text:"CREATIVE CIRCLE",contrast:1.5,color:"#f2f5f1",size:9}],["pixel-sorting-streaks",{direction:"horizontal",length:35,range:.55}]
];
const dir="/tmp/creative-circle-smoke"; await rm(dir,{recursive:true,force:true}); await mkdir(dir,{recursive:true}); const input=path.join(dir,"fixture.mp4");
function run(args:string[]){return new Promise<void>((resolve,reject)=>{const p=spawn(process.env.FFMPEG_PATH??"ffmpeg",args,{stdio:["ignore","ignore","pipe"]});let err="";p.stderr.on("data",d=>err+=d.toString());p.on("close",code=>code===0?resolve():reject(new Error(err.slice(-1800))));});}
await run(["-hide_banner","-loglevel","error","-y","-f","lavfi","-i","testsrc2=size=320x180:rate=12:duration=1","-c:v","libx264","-pix_fmt","yuv420p",input]);
let passed=0; for(let i=0;i<cases.length;i++){const [effectId,params]=cases[i]; const effect={instanceId:`smoke-${i}`,effectId,enabled:true,seed:1000+i,params};try{await run(["-hide_banner","-loglevel","error","-y","-i",input,"-an","-vf",filterForEffect(effect),"-t","0.6","-c:v","libx264","-pix_fmt","yuv420p",path.join(dir,`${i}.mp4`)]);passed++;console.log(`PASS ${i+1}/52 ${effectId}`)}catch(e){console.error(`FAIL ${i+1}/52 ${effectId}`);console.error(e instanceof Error?e.message:e)}} console.log(`${passed}/${cases.length} effect renders passed`); if(passed!==cases.length) process.exit(1);
