import type { EffectStack } from "../schema.js";

type Effect = EffectStack[number];
const n=(p:Effect["params"],k:string,d:number)=>typeof p[k]==="number"?Number(p[k]):d;
const s=(p:Effect["params"],k:string,d:string)=>typeof p[k]==="string"?String(p[k]):d;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function rand(seed:number){let t=seed|0;return()=>{t+=0x6d2b79f5;let x=t;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296}}
function snapshot(canvas:HTMLCanvasElement,temp:HTMLCanvasElement){temp.width=canvas.width;temp.height=canvas.height;temp.getContext("2d")!.drawImage(canvas,0,0)}
function restore(canvas:HTMLCanvasElement,temp:HTMLCanvasElement, filter="none", alpha=1){const c=canvas.getContext("2d")!;c.save();c.clearRect(0,0,canvas.width,canvas.height);c.filter=filter;c.globalAlpha=alpha;c.drawImage(temp,0,0);c.restore()}
function pixelate(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,size:number){const c=canvas.getContext("2d")!;snapshot(canvas,temp);const w=Math.max(1,Math.round(canvas.width/size)),h=Math.max(1,Math.round(canvas.height/size));c.imageSmoothingEnabled=false;c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(temp,0,0,w,h);c.drawImage(canvas,0,0,w,h,0,0,canvas.width,canvas.height);c.imageSmoothingEnabled=true}
function imageOp(canvas:HTMLCanvasElement, fn:(d:Uint8ClampedArray,w:number,h:number)=>void){const c=canvas.getContext("2d")!;const im=c.getImageData(0,0,canvas.width,canvas.height);fn(im.data,im.width,im.height);c.putImageData(im,0,0)}
function grayscale(canvas:HTMLCanvasElement,contrast=1){imageOp(canvas,d=>{for(let i=0;i<d.length;i+=4){let y=(d[i]*.299+d[i+1]*.587+d[i+2]*.114);y=(y-128)*contrast+128;d[i]=d[i+1]=d[i+2]=clamp(y,0,255)}})}
function threshold(canvas:HTMLCanvasElement,t=.5,contrast=1){grayscale(canvas,contrast);imageOp(canvas,d=>{const q=t*255;for(let i=0;i<d.length;i+=4){const v=d[i]<q?0:255;d[i]=d[i+1]=d[i+2]=v}})}
function posterize(canvas:HTMLCanvasElement,levels=6){const step=255/Math.max(1,levels-1);imageOp(canvas,d=>{for(let i=0;i<d.length;i+=4){d[i]=Math.round(d[i]/step)*step;d[i+1]=Math.round(d[i+1]/step)*step;d[i+2]=Math.round(d[i+2]/step)*step}})}
function addNoise(canvas:HTMLCanvasElement,amount:number,seed:number){const r=rand(seed);imageOp(canvas,d=>{for(let i=0;i<d.length;i+=4){const x=(r()-.5)*amount*255;d[i]=clamp(d[i]+x,0,255);d[i+1]=clamp(d[i+1]+x,0,255);d[i+2]=clamp(d[i+2]+x,0,255)}})}
function channelShift(canvas:HTMLCanvasElement,dx:number,dy=0){const c=canvas.getContext("2d")!;const im=c.getImageData(0,0,canvas.width,canvas.height),out=new ImageData(im.width,im.height);const d=im.data,o=out.data,w=im.width,h=im.height;for(let y=0;y<h;y++){for(let x=0;x<w;x++){const i=(y*w+x)*4;const rx=Math.max(0,Math.min(w-1,x-dx)),bx=Math.max(0,Math.min(w-1,x+dx)),gy=Math.max(0,Math.min(h-1,y+dy));o[i]=d[(y*w+rx)*4];o[i+1]=d[(gy*w+x)*4+1];o[i+2]=d[(y*w+bx)*4+2];o[i+3]=255}}c.putImageData(out,0,0)}
function edge(canvas:HTMLCanvasElement,color?:string){const c=canvas.getContext("2d")!;const im=c.getImageData(0,0,canvas.width,canvas.height),out=new ImageData(im.width,im.height),d=im.data,o=out.data,w=im.width,h=im.height;let cr=255,cg=255,cb=255;if(color?.startsWith("#")&&color.length===7){cr=parseInt(color.slice(1,3),16);cg=parseInt(color.slice(3,5),16);cb=parseInt(color.slice(5,7),16)};for(let y=1;y<h-1;y++){for(let x=1;x<w-1;x++){const p=(y*w+x)*4;const lum=(j:number)=>d[j]*.299+d[j+1]*.587+d[j+2]*.114;const gx=lum(p+4)-lum(p-4),gy=lum(p+w*4)-lum(p-w*4),m=clamp(Math.hypot(gx,gy)*1.8,0,255);o[p]=cr*m/255;o[p+1]=cg*m/255;o[p+2]=cb*m/255;o[p+3]=255}}c.putImageData(out,0,0)}
function grid(canvas:HTMLCanvasElement,step:number,color="rgba(255,255,255,.24)",width=1){const c=canvas.getContext("2d")!;c.save();c.strokeStyle=color;c.lineWidth=width;c.beginPath();for(let x=0;x<canvas.width;x+=step){c.moveTo(x,0);c.lineTo(x,canvas.height)}for(let y=0;y<canvas.height;y+=step){c.moveTo(0,y);c.lineTo(canvas.width,y)}c.stroke();c.restore()}
function scanlines(canvas:HTMLCanvasElement,step=6,alpha=.18){const c=canvas.getContext("2d")!;c.save();c.fillStyle=`rgba(0,0,0,${alpha})`;for(let y=0;y<canvas.height;y+=step)c.fillRect(0,y,canvas.width,Math.max(1,step/2));c.restore()}
function blur(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,px:number){snapshot(canvas,temp);restore(canvas,temp,`blur(${Math.max(0,px)}px)`)}
function transform(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,rotate=0,scale=1,flipX=false,dx=0,dy=0){snapshot(canvas,temp);const c=canvas.getContext("2d")!;c.save();c.clearRect(0,0,canvas.width,canvas.height);c.translate(canvas.width/2+dx,canvas.height/2+dy);c.rotate(rotate);c.scale(flipX?-scale:scale,scale);c.drawImage(temp,-canvas.width/2,-canvas.height/2);c.restore()}
function tile(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,cols:number,rows:number,gap=0){snapshot(canvas,temp);const c=canvas.getContext("2d")!;c.clearRect(0,0,canvas.width,canvas.height);const cw=canvas.width/cols,ch=canvas.height/rows;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)c.drawImage(temp,0,0,temp.width,temp.height,x*cw+gap,y*ch+gap,cw-gap*2,ch-gap*2)}
function overlayText(canvas:HTMLCanvasElement,text:string,size:number,color="white",density=1){const c=canvas.getContext("2d")!;c.save();c.font=`700 ${size}px monospace`;c.fillStyle=color;c.globalAlpha=.7;const stepX=Math.max(size*text.length*.65,30),stepY=size*1.4;for(let y=stepY;y<canvas.height;y+=stepY/density){for(let x=0;x<canvas.width;x+=stepX)c.fillText(text,x,y)}c.restore()}
function tint(canvas:HTMLCanvasElement,color:string,alpha=.25){const c=canvas.getContext("2d")!;c.save();c.globalCompositeOperation="screen";c.globalAlpha=alpha;c.fillStyle=color;c.fillRect(0,0,canvas.width,canvas.height);c.restore()}
function bandShift(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,bands:number,shift:number,time:number,seed:number){snapshot(canvas,temp);const c=canvas.getContext("2d")!,r=rand(seed+Math.floor(time*12));const bh=canvas.height/bands;c.clearRect(0,0,canvas.width,canvas.height);for(let i=0;i<bands;i++){const off=(r()-.5)*shift+Math.sin(time*3+i)*shift*.35;c.drawImage(temp,0,i*bh,temp.width,bh,off,i*bh,canvas.width,bh)}}
function thermal(canvas:HTMLCanvasElement){imageOp(canvas,d=>{for(let i=0;i<d.length;i+=4){const y=(d[i]+d[i+1]+d[i+2])/765;d[i]=clamp(255*Math.min(1,y*2),0,255);d[i+1]=clamp(255*(1-Math.abs(y-.55)*2),0,255);d[i+2]=clamp(255*Math.max(0,1-y*1.5),0,255)}})}
function hatch(canvas:HTMLCanvasElement,step:number,alpha=.45){const c=canvas.getContext("2d")!;c.save();c.strokeStyle=`rgba(0,0,0,${alpha})`;c.lineWidth=1;for(let x=-canvas.height;x<canvas.width;x+=step){c.beginPath();c.moveTo(x,0);c.lineTo(x+canvas.height,canvas.height);c.stroke()}c.restore()}

export function applyPreviewEffect(canvas:HTMLCanvasElement,temp:HTMLCanvasElement,history:HTMLCanvasElement|null,effect:Effect,time:number){const p=effect.params;const frameSeed=effect.seed+Math.floor(time*30);switch(effect.effectId){
case"horizontal-band-shift":bandShift(canvas,temp,Math.round(n(p,"bands",10)),n(p,"shift",28),time,frameSeed);break;
case"binary-grid":pixelate(canvas,temp,n(p,"size",14));threshold(canvas,n(p,"threshold",.5),n(p,"contrast",1.5));break;
case"digital-rain":grayscale(canvas,1.2);overlayText(canvas,"01",n(p,"scale",14),"#55ff77",n(p,"density",.55)+.4);break;
case"block-pixelation":pixelate(canvas,temp,n(p,"size",18));break;
case"eroded-halftone":grayscale(canvas,n(p,"contrast",1.6));addNoise(canvas,n(p,"noise",.2),frameSeed);grid(canvas,n(p,"dot",8),"rgba(0,0,0,.45)",2);break;
case"ascii-symbols":pixelate(canvas,temp,n(p,"size",14));grayscale(canvas,n(p,"contrast",1.4));overlayText(canvas,s(p,"charset","dense")==="binary"?"01":"@#%",n(p,"size",14),s(p,"colorMode","mono")==="lime"?"#a3ff12":"white",.65);break;
case"ember-glyphs":grayscale(canvas,1.5);tint(canvas,"#ff5a18",.55);addNoise(canvas,.12+n(p,"flicker",.3)*.2,frameSeed);blur(canvas,temp,n(p,"glow",8)/4);break;
case"topographic-lines":edge(canvas,s(p,"color","#a3ff12"));grid(canvas,n(p,"spacing",9)*2,"rgba(163,255,18,.18)",n(p,"thickness",1));break;
case"neon-edge-trace":edge(canvas,s(p,"color","#72e8ff"));snapshot(canvas,temp);restore(canvas,temp,`blur(${n(p,"glow",7)/4}px)`);tint(canvas,s(p,"color","#72e8ff"),.35);break;
case"repeated-crop-grid":tile(canvas,temp,Math.round(n(p,"columns",3)),Math.round(n(p,"rows",3)),n(p,"spacing",2));break;
case"cross-stitch-pixels":pixelate(canvas,temp,n(p,"size",10));grid(canvas,n(p,"size",10),"rgba(255,255,255,.24)",n(p,"thickness",2));hatch(canvas,n(p,"size",10),.22);break;
case"date-stamp-burn":{const c=canvas.getContext("2d")!;c.save();c.font=`700 ${Math.round(22*n(p,"scale",1))}px monospace`;c.fillStyle="#ff7a33";c.globalAlpha=n(p,"opacity",.85);c.fillText(s(p,"dateText","09 24 '26"),22,canvas.height-28);c.restore();break}
case"variable-dot-matrix":pixelate(canvas,temp,n(p,"grid",10));grid(canvas,n(p,"grid",10),"rgba(0,0,0,.34)",2);break;
case"mirror-side-panels":transform(canvas,temp,0,1,true);blur(canvas,temp,n(p,"blur",6)/3);break;
case"polygon-fragmentation":transform(canvas,temp,n(p,"rotation",8)*Math.PI/180,1,false,n(p,"displacement",22)/4,0);grid(canvas,Math.max(20,240/n(p,"count",12)),"rgba(0,0,0,.65)",n(p,"gap",2));break;
case"progressive-blur":blur(canvas,temp,n(p,"blur",12)/3);break;
case"glitch-bloom":channelShift(canvas,Math.round(n(p,"chromatic",5)));bandShift(canvas,temp,7,n(p,"displacement",15),time,frameSeed);blur(canvas,temp,n(p,"radius",7)/8);break;
case"datamosh-smear":if(history){const c=canvas.getContext("2d")!;c.save();c.globalAlpha=n(p,"feedback",.65);c.globalCompositeOperation="screen";c.drawImage(history,n(p,"displacement",12)/3,0);c.restore()}pixelate(canvas,temp,n(p,"block",16));break;
case"motion-study-grid":if(history){snapshot(canvas,temp);const c=canvas.getContext("2d")!;c.clearRect(0,0,canvas.width,canvas.height);const w=canvas.width/2,h=canvas.height/2;c.drawImage(temp,0,0,w,h);c.drawImage(history,w,0,w,h);c.drawImage(history,0,h,w,h);c.drawImage(temp,w,h,w,h)}break;
case"film-gate-flicker":{const c=canvas.getContext("2d")!;c.save();c.globalCompositeOperation="screen";c.fillStyle=`rgba(255,245,210,${.05+Math.abs(Math.sin(time*17))*n(p,"flicker",.3)*.16})`;c.fillRect(0,0,canvas.width,canvas.height);c.restore();addNoise(canvas,n(p,"grain",.18),frameSeed);transform(canvas,temp,0,1,false,Math.sin(time*5)*n(p,"weave",2),0);break}
case"ghost-double-print":if(history){const c=canvas.getContext("2d")!;c.save();c.globalAlpha=n(p,"opacity",.45);c.globalCompositeOperation="screen";c.drawImage(history,n(p,"x",8),n(p,"y",4));c.restore()}break;
case"diagonal-frame-fracture":transform(canvas,temp,n(p,"angle",28)*Math.PI/180*.08,1.03,false,n(p,"displacement",20)/4,0);hatch(canvas,24,.25);break;
case"technical-pen-hatching":grayscale(canvas,n(p,"contrast",1.5));hatch(canvas,n(p,"density",8),.48);if(n(p,"cross",.35)>.2){transform(canvas,temp,0,1,true);hatch(canvas,n(p,"density",8),.25)}break;
case"thermal-hud":thermal(canvas);grid(canvas,64,"rgba(163,255,18,.35)",1);{const c=canvas.getContext("2d")!;c.strokeStyle="#a3ff12";c.strokeRect(canvas.width*.2,canvas.height*.18,canvas.width*.25,canvas.height*.35);c.beginPath();c.arc(canvas.width/2,canvas.height/2,32,0,Math.PI*2);c.stroke()}break;
case"fisheye-lens":{const strength=n(p,"strength",.3);transform(canvas,temp,0,1+strength*.15,false);break}
case"wavy-scanlines":bandShift(canvas,temp,Math.max(4,canvas.height/n(p,"spacing",6)),n(p,"amplitude",8),time,frameSeed);scanlines(canvas,n(p,"spacing",6),.16);break;
case"luminance-flow":edge(canvas,"#f2f5f1");blur(canvas,temp,n(p,"length",12)/8);hatch(canvas,n(p,"density",8)*2,.15);break;
case"particle-reconstruction":pixelate(canvas,temp,Math.max(3,n(p,"size",3)*2));addNoise(canvas,.06+n(p,"movement",3)/100,frameSeed);grid(canvas,Math.max(6,36-n(p,"count",1200)/80),"rgba(255,255,255,.15)",1);break;
case"mirror-double-exposure":if(history){transform(canvas,temp,0,1,true);const c=canvas.getContext("2d")!;c.globalAlpha=n(p,"opacity",.55);c.globalCompositeOperation="screen";c.drawImage(history,0,0);c.globalAlpha=1;c.globalCompositeOperation="source-over"}break;
case"monochrome-dither":threshold(canvas,n(p,"threshold",.5),n(p,"contrast",1.4));addNoise(canvas,.06,frameSeed);break;
case"machine-vision-overlay":{grid(canvas,80,"rgba(163,255,18,.24)",1);const c=canvas.getContext("2d")!;c.strokeStyle=s(p,"color","#a3ff12");c.lineWidth=n(p,"thickness",1);c.strokeRect(canvas.width*.18,canvas.height*.2,canvas.width*.24,canvas.height*.34);c.strokeRect(canvas.width*.56,canvas.height*.42,canvas.width*.22,canvas.height*.28);if(p.labels!==false)overlayText(canvas,"TRACK",9,s(p,"color","#a3ff12"),.35);break}
case"quantized-pixel-art":pixelate(canvas,temp,n(p,"resolution",14));posterize(canvas,n(p,"palette",8));break;
case"magazine-halftone":grayscale(canvas,n(p,"contrast",1.4));grid(canvas,n(p,"frequency",8),"rgba(0,0,0,.5)",Math.max(1,n(p,"size",4)/2));break;
case"crt-phosphor-mesh":channelShift(canvas,1);scanlines(canvas,Math.max(3,n(p,"mesh",3)*2),n(p,"scanline",.4)*.45);blur(canvas,temp,n(p,"glow",5)/10);break;
case"cmyk-misregistration":channelShift(canvas,Math.round(Math.abs(n(p,"magenta",5))));addNoise(canvas,n(p,"texture",.18)*.25,frameSeed);break;
case"retro-lcd-screen":pixelate(canvas,temp,n(p,"cell",7));tint(canvas,s(p,"tint","#b7d46a"),.28);if(history){const c=canvas.getContext("2d")!;c.globalAlpha=n(p,"ghosting",.35);c.drawImage(history,2,0);c.globalAlpha=1}scanlines(canvas,n(p,"cell",7),.15);break;
case"rgb-prism-slices":channelShift(canvas,Math.round(n(p,"separation",8)));bandShift(canvas,temp,n(p,"slices",8),n(p,"displacement",12),time,frameSeed);break;
case"relief-grid-3d":edge(canvas,"#ffffff");transform(canvas,temp,-.05,1.02,false,n(p,"depth",8)/2,n(p,"depth",8)/3);grid(canvas,n(p,"density",10)*2,"rgba(255,255,255,.2)",1);break;
case"analog-scan-tear":bandShift(canvas,temp,Math.max(6,Math.round(canvas.height/n(p,"height",16))),n(p,"shift",20),time,frameSeed);channelShift(canvas,Math.round(n(p,"shift",20)/7));addNoise(canvas,n(p,"noise",.15),frameSeed);break;
case"screen-print-layers":posterize(canvas,n(p,"layers",3)+1);channelShift(canvas,Math.round(n(p,"offset",3)));addNoise(canvas,n(p,"texture",.25)*.15,frameSeed);break;
case"liquid-ink-bleed":blur(canvas,temp,n(p,"radius",7)/2);grayscale(canvas,1.7);break;
case"geometric-masks":{snapshot(canvas,temp);const c=canvas.getContext("2d")!;c.save();c.clearRect(0,0,canvas.width,canvas.height);const count=Math.round(n(p,"count",8)),r=n(p,"size",.25)*Math.min(canvas.width,canvas.height);for(let i=0;i<count;i++){const rr=rand(effect.seed+i);const x=rr()*canvas.width,y=rr()*canvas.height;c.save();c.beginPath();if(s(p,"shape","circles")==="rectangles")c.rect(x-r/2,y-r/2,r,r);else c.arc(x,y,r/2,0,Math.PI*2);c.clip();c.drawImage(temp,0,0);c.restore()}c.restore();break}
case"risograph-dots":posterize(canvas,4);channelShift(canvas,Math.round(n(p,"offset",4)));grid(canvas,n(p,"frequency",8),"rgba(0,0,0,.26)",1);addNoise(canvas,n(p,"noise",.18)*.15,frameSeed);break;
case"survey-data-overlay":grid(canvas,n(p,"grid",40),`rgba(114,232,255,${n(p,"opacity",.65)*.5})`,n(p,"thickness",1));{const c=canvas.getContext("2d")!;c.strokeStyle="#72e8ff";c.strokeRect(canvas.width*.1,canvas.height*.1,canvas.width*.8,canvas.height*.8);overlayText(canvas,"N 47.00  E 120.00",9,"#72e8ff",.3)}break;
case"vhs-tape-damage":pixelate(canvas,temp,2);channelShift(canvas,Math.round(n(p,"chroma",5)));addNoise(canvas,n(p,"noise",.2),frameSeed);scanlines(canvas,4,.16);bandShift(canvas,temp,12,n(p,"damage",.4)*18,time,frameSeed);break;
case"woven-thread-pixels":pixelate(canvas,temp,n(p,"size",8));grid(canvas,n(p,"size",8),"rgba(255,255,255,.3)",n(p,"thickness",2));hatch(canvas,n(p,"size",8),.18);break;
case"mosaic-tile-scatter":pixelate(canvas,temp,n(p,"tile",18));transform(canvas,temp,n(p,"rotation",8)*Math.PI/180*.04,1.02,false,n(p,"scatter",18)/6,0);grid(canvas,n(p,"tile",18),"rgba(0,0,0,.5)",n(p,"gap",2));break;
case"puzzle-collage":grid(canvas,Math.max(20,260/n(p,"pieces",12)),"rgba(255,255,255,.7)",n(p,"border",1));bandShift(canvas,temp,Math.round(Math.sqrt(n(p,"pieces",12))*2),n(p,"displacement",14),time,effect.seed);break;
case"slit-scan-time-slices":if(history){snapshot(canvas,temp);const c=canvas.getContext("2d")!,vertical=s(p,"direction","vertical")==="vertical",step=n(p,"width",10);for(let i=0;i<(vertical?canvas.width:canvas.height);i+=step){if((i/step)%2<1){if(vertical)c.drawImage(history,i,0,step,canvas.height,i,0,step,canvas.height);else c.drawImage(history,0,i,canvas.width,step,0,i,canvas.width,step)}}}break;
case"photocopier-toner":threshold(canvas,n(p,"threshold",.5),n(p,"contrast",2));addNoise(canvas,n(p,"noise",.25)*.35,frameSeed);scanlines(canvas,15,n(p,"streaking",.2)*.35);break;
case"microtext-portrait":grayscale(canvas,n(p,"contrast",1.5));overlayText(canvas,s(p,"text","CREATIVE CIRCLE"),n(p,"size",9),s(p,"color","#f2f5f1"),n(p,"density",.65));break;
case"pixel-sorting-streaks":blur(canvas,temp,n(p,"length",35)/7);if(s(p,"direction","horizontal")==="vertical")transform(canvas,temp,Math.PI/2,1);break;
}}
